name: Build Android APK

on:
  workflow_dispatch: # Permite que você rode o robô manualmente clicando em um botão

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando o codigo
        uses: actions/checkout@v4

      - name: Configurando o Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dando permissao ao Gradle
        run: chmod +x gradlew

      - name: Compilando o aplicativo
        run: ./gradlew assembleDebug

      - name: Salvando o APK gerado
        uses: actions/upload-artifact@v4
        with:
          name: Android Auto
          path: app/build/outputs/apk/**/*.apk
